services:
  - docker

script:
  - echo $TRAVIS_SECURE_ENV_VARS
  - bash dockerlogin.sh
  - commitId=$(git log -1 --pretty=%H)
  - echo $commitId
  - NAME=aaalquis/akamaibaseline
  - echo $NAME
  - docker build -t $NAME:$commitId .
  - docker tag latest $NAME:$commitId
  - docker push $NAME 